// This file was generated by tfxjs
const tfxjs = require("tfxjs");
const tfx = new tfxjs(
  "../example-tests",
  {}
);

tfx.plan("tfx Generated Plan", () => {
  
  tfx.module(
    "Root Module",
    'root_module',
    tfx.resource(
      "Count Example 0",
      'null_resource.count_example[0]',
      {
        "triggers": {
          "trigger_value": "this-is-a-test"
        }
      }
    ),
    tfx.resource(
      "Count Example 1",
      'null_resource.count_example[1]',
      {
        "triggers": {
          "trigger_value": "this-is-a-test"
        }
      }
    ),
    tfx.resource(
      "Count Example 2",
      'null_resource.count_example[2]',
      {
        "triggers": {
          "trigger_value": "this-is-a-test"
        }
      }
    ),
    tfx.resource(
      "Map Example Example",
      'null_resource.map_example[\"example\"]',
      {
        "triggers": {
          "trigger_value": "this-is-a-test"
        }
      }
    ),
    tfx.resource(
      "Map Example Test",
      'null_resource.map_example[\"test\"]',
      {
        "triggers": {
          "trigger_value": "this-is-a-test"
        }
      }
    ),
    tfx.resource(
      "Map Example Value",
      'null_resource.map_example[\"value\"]',
      {
        "triggers": {
          "trigger_value": "this-is-a-test"
        }
      }
    ),
    tfx.resource(
      "Random Example",
      'random_pet.random_example',
      {
        "length": 3,
        "prefix": "example-acceptance",
        "separator": "-"
      }
    ),
    tfx.resource(
      "Shuffle Example List 1",
      'random_shuffle.shuffle_example[\"list_1\"]',
      {
        "input": [
          "ponder",
          "consider",
          "opt",
          "preordain",
          "brainstorm",
          "portent"
        ],
        "keepers": {
          "shuffle_count": "2"
        },
        "result_count": 2
      }
    ),
    tfx.resource(
      "Shuffle Example List 2",
      'random_shuffle.shuffle_example[\"list_2\"]',
      {
        "input": [
          "scout",
          "slinger",
          "warrior",
          "builder",
          "settler"
        ],
        "keepers": {
          "shuffle_count": "2"
        },
        "result_count": 2
      }
    ),
  );
  
  tfx.module(
    "Example Module",
    'module.example_module',
    tfx.resource(
      "Random Example",
      'random_pet.random_example',
      {
        "length": 2,
        "prefix": "acceptance-module",
        "separator": "-"
      }
    ),
  );
});
